# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tbgKW_cLgVIhK6la7RPsXKlUqke8s_RO
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/WHO-COVID-19-global-data.csv")
df

df.loc[:,["New_cases","Cumulative_cases"]]

df.plot(kind="bar",x='New_cases', color='red')
plt.show()

df.plot(kind="bar",x="New_cases",y="New_deaths")

df[["New_deaths"]].plot(kind="hist",bins=[0,20,40,60,80,100],rwidth=0.8)
plt.show()

import matplotlib.ticker as mtick
sns.set_style("darkgrid")
plt.rc('axes', titlesize=20)
plt.rc('axes',labelsize=14)
plt.rc('xtick',labelsize=13)
plt.rc('ytick', labelsize=13)
plt.rc('font',size=13)

sns.color_palette("deep")

sns.color_palette("pastel")

sns.color_palette('Set2')

plt.figure(figsize=(10,5),tight_layout=True)
colors=sns.color_palette('pastel')
plt.bar('New_cases',height=15, color=colors[:])
plt.xlabel("New_cases")
plt.ylabel("New_deaths")
plt.title('Barplot')
plt.show()